### ISSUE TITLE
https://discord.gg/JADBAZzkMz

### ISSUE THREAD

**Issue by Flxsher** [i0Z3R0/Discord-Server-Members#1]
Server Name: 
Server Approximate Total Member Count: 
Server Approximate Online Member Count: 
Server Invite Link (non-expiring or vanity): 
Make Database Public?*: 

*If so, I will add it to the Databases folder and everyone can access it. If you would like to, provide with me some method of communication (Discord etc.) and I will privately give you the file.

**Comment by Flxsher** [comment]
.

**Comment by i0Z3R0** [comment]
Done
https://github.com/i0Z3R0/Discord-Server-Members/tree/main/Database/Github%20Requests/Gold%20Shop%20GR
